const ejerciciosNombre = [
    "Press de banca con barra",
    "Press banca inclinado con mancuernas",
    "Cruce de poleas",
    "Press de banca inclinado con barra",
    "Press de banca con mancuernas",
    "Aperturas con mancuernas",
    "Aperturas Inclinadas con mancuernas",
    "Press de banca en máquina sentado",
    "Press de banca declinado con barra",
    "Press de banca declinado con mancuernas",
    "Flexiones",
    "Fondos en barras paralelas",
    "Aperturas en máquina Peck Deck o Contractora",
    "Remo con mancuerna a una mano",
    "Jalón con agarre ancho",
    "Remo en máquina",
    "Jalón al pecho con agarre cerrado",
    "Remo con barra",
    "Jalón tras nuca",
    "Jalón al pecho con agarre invertido",
    "Jalón en polea con cuerda",
    "Remo en barra T",
    "Remo inclinado con barra con agarre supinado",
    "Elevaciones en barra fija",
    "Elevaciones tras nuca en barra fija",
    "Elevaciones en barra fija con agarre supinado",
    "Jalón dorsal con brazos rectos",
    "Remo inclinado con mancuernas",
    "Peso muerto con barra",
    "Peso muerto sumo con barra",
    "Peso muerto con barra hexagonal",
    "Peso muerto con mancuernas",
    "Encogimiento de hombros con barra",
    "Encogimiento de hombros con mancuernas",
    "Press de hombro con mancuernas",
    "Elevación lateral con mancuernas",
    "Elevación frontal con mancuernas",
    "Cruces inversos en polea alta",
    "Press de hombros en Máquina Smith",
    "Remo alto con barra",
    "Elevaciones posteriores para hombros (Pájaro)",
    "Elevación lateral con cable a una mano",
    "Press Militar con mancuernas",
    "Press Militar",
    "Elevaciones frontales con cable a una mano",
    "Elevaciones frontales con barra",
    "Press militar sentado con barra",
    "Press tras nuca sentado",
    "Press militar de pie",
    "Press militar de pie tras nuca",
    "Elevación frontal con mancuernas alternas agarre neutro",
    "Elevación frontal con un brazo en polea baja agarre neutro",
    "Elevación frontal con mancuerna a dos manos",
    "Curl con cuerda en polea",
    "Curl con barra EZ",
    "Curl de predicador con barra EZ",
    "Curl alterno de martillo con mancuernas",
    "Curl inclinado con mancuernas",
    "Curl concentrado con mancuernas",
    "Curl de cable en polea baja a una mano",
    "Curl de cable con barra recta en polea baja",
    "Curl de cable en polea alta de pie",
    "Curl de muñeca con barra sentado",
    "Extensión de muñeca con barra sentado",
    "Curl de barra invertido",
    "Crunch",
    "Crunch oblicuo",
    "Abdominales en máquina",
    "Abdominales con cuerda en polea alta",
    "Plancha",
    "Elevación de piernas",
    "Encogimientos de rodillas para abdominales",
    "Abdominales con brazos estirados",
    "Plancha con flexión",
    "Sentadilla",
    "Prensa de piernas",
    "Extensión de piernas",
    "Zancada",
    "Curl de pierna tumbado en máquina de femoral",
    "Sentadilla Hack",
    "Curl de piernas sentado",
    "Extensión a una pierna",
    "Sentadilla frontal",
    "Peso muerto rumano (piernas rectas) con mancuernas",
    "Peso muerto rumano (piernas rectas) con barra",
    "Sentadilla Goblet con mancuerna",
    "Salto Rodillas al Pecho",
    "Burpees",
    "Sentadillas con propio peso",
    "1.5 repeticiones de sentadillas con propio peso",
    "Sentadillas con balón medicinal",
    "Sentadilla búlgara con barra",
    "Sentadilla búlgara con propio peso",
    "Sentadilla con mini banda",
    "Sentadilla con salto",
    "Sentadilla isométrica apoyado sobre la pared",
    "Peso muerto con balón medicinal",
    "Peso muerto a una pierna",
    "Sentadilla sumo con kettlebell",
    "Ejercicio 'buenos días' con barra",
    "Puente con propio peso",
    "Puentes a una pierna",
    "Puente con bandas",
    "Caminata de pato",
    "Ejercicio Superman en cuadrupedia",
    "Los Groiners",
    "Hidrantes",
    "Hip thrust con maquina Smith",
    "Hip thrust con barra",
    "Abducciones de cadera sentado con banda",
    "Abducción de cadera con máquina de abducción de cadera",
    "Abducción con polea",
    "Elevaciones en posición de rana con propio peso",
    "Elevaciones cortas en posición de rana con maquina Smith",
    "Almejas laterales con banda",
    "Levantamiento de pierna acostado de lado",
    "Elevaciones de bíceps femoral con máquina GHD",
    "Step Up con mancuernas",
    "Caminata lateral con minibanda",
    "Elevaciones de rodilla",
    "Columpios con kettlebell",
    "Contragolpe con cable",
    "Patadas de burro",
    "Elevaciones de cadera acostado lateralmente",
    "Sentadilla Posturas funcionales",
    "Elevación de gemelos sentado",
    "Elevación de gemelos de pie"
]
export default ejerciciosNombre